"""py2app build config for "Voca.app".

Build with the helper script (recommended):

    ./build_app.sh

or directly in alias mode (references this project/venv in place — fast, not
relocatable, perfect for personal use):

    .venv/bin/python setup.py py2app -A

Alias mode matters: py2app places a real Python stub as the bundle's main
executable inside Contents/MacOS, so macOS attributes Microphone / Accessibility
permissions to *this app* rather than to the shared framework Python.app.
"""

import ast
from pathlib import Path

from setuptools import setup


def _version() -> str:
    """Read __version__ from dictate/__init__.py without importing the package."""
    src = Path(__file__).parent / "dictate" / "__init__.py"
    for line in src.read_text(encoding="utf-8").splitlines():
        if line.startswith("__version__"):
            return ast.literal_eval(line.split("=", 1)[1].strip())
    return "0.0.0"


VERSION = _version()

APP = ["run_menubar.py"]

OPTIONS = {
    "argv_emulation": False,
    # Waveform app icon (generated by assets/make_icon.py). py2app copies this
    # into the bundle and sets CFBundleIconFile on a fresh build.
    "iconfile": "assets/AppIcon.icns",
    "plist": {
        "CFBundleName": "Voca",
        "CFBundleDisplayName": "Voca",
        "CFBundleIdentifier": "com.voca.app",
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": VERSION,
        # Menu-bar agent: no Dock icon, no window.
        "LSUIElement": True,
        "LSMinimumSystemVersion": "13.0",
        "NSMicrophoneUsageDescription": (
            "Voca records audio while you hold the fn key so it can "
            "transcribe your speech on-device."
        ),
        "NSHighResolutionCapable": True,
        # LaunchServices starts apps with no locale, so Python defaults file I/O to
        # ASCII and chokes on any non-ASCII text (e.g. transcripts, the … glyph).
        # Force UTF-8 everywhere. These are read at interpreter startup, so they
        # must be set in the bundle environment, not at runtime.
        "LSEnvironment": {
            "PYTHONUTF8": "1",
            "PYTHONIOENCODING": "utf-8",
            "LANG": "en_US.UTF-8",
            "LC_ALL": "en_US.UTF-8",
        },
    },
}

setup(
    name="Voca",
    app=APP,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
